Makefile, README.md, examples/dimensions/main.go, examples/features/main.go, table/border.go, table/header.go, table/row.go, table/table.go, table/table_test.go
Addresses #7 
Use a nicer method of generating and applying border styles, along with allowing custom borders to be supplied.
=> Add border customization and refactor existing border code

.github/workflows/coverage.yml, README.md
Adds test coverage as a workflow using Coveralls
=> Coverage workflow

README.md, examples/features/main.go, table/cell.go, table/column.go, table/row.go, table/view.go, table/view_test.go
Closes #19 
Adds support for column and cell styling.
=> Cell and column styling

examples/features/main.go, table/model.go, table/options.go, table/row.go, table/strlimit.go, table/strlimit_test.go, table/view_selectable_test.go
=> Make the selectable text customizable

examples/sorting/main.go, table/model_test.go, table/sort.go
Missed a bit of documentation for public methods, and cleared up a few copy/paste errors.
=> Some extra sort docs for clarity

README.md, examples/features/main.go, table/border.go, table/column.go, table/footer.go, table/model.go, table/options.go, table/row.go, table/view.go, table/view_test.go
Note that this currently does not work with alignment due to unexpected behavior in lipgloss: https://github.com/charmbracelet/lipgloss/issues/70
=> Add base style

Makefile, README.md, examples/flex/main.go, table/benchmarks_test.go, table/calc.go, table/calc_test.go, table/column.go, table/dimensions.go, table/dimensions_test.go, table/filter.go, table/model.go, table/options.go, table/row.go, table/view.go, table/view_test.go
Closes #3 
Implements flexbox-style columns as well as an example.
=> Flexbox style column widths

table/options.go, table/options_test.go, table/update.go
Allow setting which row will be highlighted by passing its index
=> Add function to set the highlighted row - fixes issue #42

table/calc_test.go, table/options_test.go
Bumping back up for a bit of extra coverage.
=> A bit of extra test coverage

CONTRIBUTING.md, README.md
There's been a few people helping out now, so hopefully this will help in the future.
=> Add quick contributing notes

examples/pagination/main.go, table/options.go, table/options_test.go
Adds various programmatic calls to control pagination.
* PageDown
* PageUp
* PageFirst
* PageLast
* WithCurrentPage
=> Add programmatic options for pagination controls

examples/updates/main.go, table/options.go, table/view_test.go
Helps #59 while providing the ability to resize, add, and remove columns too.
=> Add WithColumns option

table/column.go
Helps #58 , forgot to add this when updating the example as well.
=> Add doc comment for flex columns to use WithTargetWidth

Makefile, README.md, examples/metadata/main.go
Better documentation to support #74
=> Add metadata example

examples/scrolling/README.md, examples/scrolling/main.go, table/header.go, table/model.go, table/options.go, table/row.go, table/scrolling.go, table/update_test.go
Adds ability to freeze left columns with horizontal scrolling.  Should help close #83
=> Add horizontal freeze

table/options.go, table/update_test.go
Related to #83 , just add some quick accessors to be able to programmatically scroll left/right.
=> Add programmatic access to scroll left and right

README.md
Add a link and note in the main readme to make horizontal scrolling more discoverable.  Helps #83
=> Quick readme update for horizontal scrolling

table/row.go, table/view_test.go
Helps #83 
Always right-align the right scroll caret for consistency.
=> Right-align caret

table/scrolling_test.go
Test case for #79 to ensure that keybinds are working properly for scrolling.  No functional changes, just verification.
=> Add test for scrolling with custom keybinds

examples/scrolling/main.go
Makes for a helpful playground for testing #83 so we can better find edge cases with interactive testing.
=> Make the scrolling example more easily configurable for testing/playing

README.md, examples/metadata/main.go, examples/pokemon/main.go, table/border.go, table/view_test.go
To celebrate hitting 100 PRs/issues 🎊 
Fixes #50
=> Add rounded border as option

README.md, examples/features/main.go, table/border.go, table/footer.go, table/model.go, table/options.go, table/options_test.go, table/query.go, table/query_test.go, table/view.go, table/view_test.go
Adds an option to turn header visibility on or off.
=> Header visibility option

examples/events/main.go, table/events.go, table/events_test.go, table/update.go
Adds a user event for a row selection being toggled.
=> Row select toggle event

table/model.go, table/options.go, table/pagination.go, table/query.go, table/query_test.go, table/update_test.go
Helps #112 
Adds option to set whether pagination wraps or not.  Defaults to true to keep current behavior.
=> Add option to toggle whether pagination wraps

README.md, examples/pokemon/main.go
Use the new format string in the main example as it looks nicer.
=> Main example percent format

table/filter.go, table/filter_test.go
Before:
If I using filter on StyledCell, it will show nothing.
After fixing:
filter works.
=> fix: filter not works when using StyledCell

table/row.go
Closes https://github.com/Evertras/bubble-table/issues/140
=> Update row select docs to be clearer

table/options.go, table/options_test.go
=> Add option to deselect programmatically

.gitignore
Just a quick gitignore so we can have an experimenting area without worrying about git adding our experiments.
=> Allow a sandbox area for easier experimenting

table/filter.go
Small optimization for large numbers of rows, asking for `Value()` is nontrivial according to profiler
=> Don't check filter input value for each row

table/pagination.go, table/update.go
We only need to update this when things actually change, not on every possible update ever...
=> Don't reset the cache on every single update

.github/workflows/build.yml, .github/workflows/coverage.yml
Go setup has also jumped two versions ahead, so update it.
=> Update go setup actions

table/footer.go, table/overflow.go
This PR fixes a couple of issues:
- Horizontal scrolling was broken, I managed to track it down to an incorrect style assignment (fixes #181)
- A footer related test was failing, turned out to be another style assignment issue.
p.s. thanks for this component, it's by far the best table implementation I've found for bubbletea, and I'm using it extensively in my app!
=> Horizontal scrolling fix

table/keys.go, table/keys_test.go, table/model.go, table/options.go
So as discussed in #184 this is a first attempt at including this. 
I didn´t really know where to put the tests so I made a new file, hope that structure works for you.
The naming, as well as testing / layout etc. is all changeable, just wanted to provide a first look at how this interface could be provided.
Let me know what you think.
=> Added functionality to implement help.KeyMap interface

table/filter_test.go, table/options.go
Adds test for #175 and invalidates cache when a filter func is modified.
=> Invalidate cache when filter func applied and add test

examples/pokemon/main.go
My quick copy/pasting was dumb and verbose, make this nicer as an example by using a map from key to color.
=> Nicer pokemon example for coloring

Makefile, table/filter.go, table/filter_test.go, table/model.go, table/options.go
cc @IAL32
Given we just changed the filter func signature, I changed it again before the new signature could really be used so that we can in the future change this much more easily. This is also the pattern of what the style funcs use, so it increases consistency as well.
=> Filterfunc with input
