examples/dimensions/main.go, examples/features/main.go, table/border.go, table/column.go, table/row.go, table/table.go, table/table_test.go
'Header' was a mental shortcut name that is unclear.  These are actually columns, so call them columns.
=> Rename header to column for clarity

Makefile, README.md, examples/features/main.go, examples/pagination/main.go, table/footer.go, table/keys.go, table/model.go, table/options.go, table/pagination.go, table/pagination_test.go, table/row.go, table/update.go, table/update_test.go, table/view.go, table/view_test.go
Closes #1 
Adds pagination as an option to enable.
Includes default keys to move between pages.
Follows highlighted row movement through pages.
=> Pagination

Makefile, README.md, examples/features/main.go, examples/sorting/main.go, table/data.go, table/data_test.go, table/model.go, table/options.go, table/row.go, table/sort.go, table/sort_test.go, table/view_test.go
Adds sorting options.
Sorts by numbers if they're numbers, otherwise sorts by string values.
Allows sorting using multiple columns chained together in either ascending or descending order.
=> Programmatic Sorting

table/update.go, table/update_test.go
Selection was broken by the sort functionality.  This is a quick fix since #29 will adjust how sorted rows are stored in the back-end.
=> Fix selection

examples/filter/main.go, go.mod, go.sum, table/border.go, table/column.go, table/filter.go, table/filter_test.go, table/footer.go, table/keys.go, table/model.go, table/model_test.go, table/options.go, table/pagination.go, table/pagination_test.go, table/row.go, table/sort.go, table/sort_test.go, table/update.go, table/update_test.go
Request https://github.com/Evertras/bubble-table/issues/5 is done.
demo `go run examples/filter/main.go`.
```
A filtered simple default table
Currently filter by:
Press q or ctrl+c to quit
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━┓
┃        Title┃       Author┃Desc…┃
┣━━━━━━━━━━━━━╋━━━━━━━━━━━━━╋━━━━━┫
┃Computer Sys…┃Randal E. Br…┃This…┃
┃Effective Ja…┃ Joshua Bloch┃The …┃
┃Structure an…┃Harold Abels…┃Stru…┃
┃Game Program…┃Robert Nystr…┃The …┃
┣━━━━━━━━━━━━━┻━━━━━━━━━━━━━┻━━━━━┫
┃                              1/1┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
A filtered simple default table
Currently filter by:
Press q or ctrl+c to quit
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━┓
┃        Title┃       Author┃Desc…┃
┣━━━━━━━━━━━━━╋━━━━━━━━━━━━━╋━━━━━┫
┃Computer Sys…┃Randal E. Br…┃This…┃
┃Structure an…┃Harold …
```
=> feat: filter feature works

examples/flex/main.go, table/strlimit.go, table/strlimit_test.go
https://github.com/Evertras/bubble-table/issues/40
Implemented the go-runewidth library to manage runes truncation
Added tests for japanese characters
=> Fix string length limiting for double-width characters

examples/flex/main.go, table/dimensions.go, table/footer.go, table/view_test.go
A static footer wasn't rendering properly with flex columns due to the width being calculated incorrectly and at the wrong time.  This makes things a little clearer in terms of what `totalWidth` actually means (it's the full visible width of the table) and makes it work more nicely with the target flex width.
=> Fix flex footer

table/strlimit.go, table/strlimit_test.go
If one of the rows has a multi-line value we want
to truncate it and display one the first line
=> Fix table layout for multi-line values - fixes issue #51

table/strlimit.go, table/strlimit_test.go
Fixes the edge case remaining for #51 where in a multiline string, if the first line was exactly the max width, the extra added character would break the format.
=> Fix edge case for multiline truncation on exact max length

examples/flex/main.go
The flex column example didn't clarify that it also requires `WithTargetWidth`, so make that more clear.  Helps #58
=> Add a comment to the flex column example

examples/filter/main.go, table/keys.go, table/update.go, table/update_test.go
Escape key will now exit filtering, as well as clear the filter if not currently actively typing in the filter.  Clearing the filter is a configurable keymap.
This is theoretically a breaking change if someone was using the escape key along with table filtering and expected some other behavior, but this seems incredibly unlikely and the keymap can be redone in their application if this is the case.
=> Add shortcut to clear filter and escape filtering

table/model.go, table/query.go, table/query_test.go, table/sort.go, table/sort_test.go
Helps #60 
Adds some non-mutable queries for current state of sorting and filtering.
=> Add some basic queries for sorting and filtering

go.mod, table/strlimit.go, table/strlimit_test.go
PR related to #66.
Based on [this comment](https://github.com/Evertras/bubble-table/issues/66#issuecomment-1113884401) I looked in the muesli/reflow library for utilities to compute string width & do truncation while accounting for ANSI control sequences.
I would be happy to resubmit this PR using lipgloss instead if you'd prefer.
=> Use muesli/reflow to compute str width & truncate

examples/pagination/main.go, table/options.go, table/pagination_test.go
Related to #69 
Shows an example of resizing pages dynamically to adjust table height.  Fixes an edge case where increasing the page size could leave the user on a page beyond the last.
=> Add example of changing page size dynamically and fix edge case

examples/filterapi/main.go, table/filter_test.go, table/footer.go, table/model.go, table/options.go, table/options_test.go
We already have keyword filtering, but this can only be displayed in the footer of the form. If I want a form without a footer, or if I want to have the ability to manually control the filtering feature, I need an API to connect to the form to manipulate it.
Before:
```
A filtered simple default table
Currently filter by Title and Author, press / + letters to start filtering, and escape to clear filter.
Press q or ctrl+c to quit
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Title┃       Author┃                                       Description┃
┣━━━━━━━━━━━━━╋━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃Computer Sys…┃Randal E. Br…┃This book explains the important and enduring con…┃
┃Structure an…┃Harold Abels…┃Structure and …
```
=> enable filter works with table api(not in the footer)

table/options.go
The app that I'm building has an initial screen where you can select different "providers" for things, and then for each provider it will jump to another screen where it shows a list of items in a table. The table gets created once, and then every time a provider is selected the contents get refreshed doing something like this:
```go
m.table = m.table.WithRows(rows)
```
That has been working pretty well, however, I've found that if I had previously selected rows, when changing the displayed rows the selection isn't cleared up.
You can reproduce it by applying this diff to `examples/features/main.go`:
```patch
examples/features/main.go | 9 +++++++++
1 file changed, 9 insertions(+)
diff --git a/examples/features/main.go b/examples/features/main.go
index cecfc74..42bb411 100644
--- …
```
=> Fix bug: previously selected rows aren't cleared up after calling `WithRows`

README.md, table/row.go
The ability to attach metadata existed, and an example was recently added, but it was difficult to find.  So we should add some more obvious hooks from both the readme and to the data struct itself for docs purposes.
Should finish off #74 for now.
=> Better docs for metadata

Makefile, README.md, examples/dimensions/README.md, examples/features/README.md, examples/filter/README.md, examples/filterapi/README.md, examples/flex/README.md, examples/metadata/README.md, examples/pagination/README.md, examples/pokemon/README.md, examples/simplest/README.md, examples/sorting/README.md, examples/updates/README.md
Adds readmes/screenshots/gifs to all examples, and updates the main README to point to the READMEs of the examples rather than directly to the code.
Closes #78
=> Add visual examples and readmes for all examples

examples/scrolling/main.go, table/footer.go, table/options_test.go, table/view.go, table/view_test.go
As described in #83 , the footer would sometimes be too large when scrolled to the right.  This makes the footer always match the table's actual width.
=> Fix footer size with horizontal scrolling

table/model.go, table/options.go, table/options_test.go, table/row.go, table/update.go
Add a new `Row.Selected(bool) Row` function that allows to indicate if the row is selected or not in a programatic manner. In addition to this it:
* refactors the way `Model.SelectedRows() []Row` works by computing the selected rows whenever this method is called instead of when the mark is toggled;
* adds test for selecting rows programatically;
* adds benchmark for `Model.SelectedRows()`
* reduce some allocations in `Model.SelectedRows`
As a byproduct of these changes, the previously reported and fixed bug #80 won't reappear again.
=> Feature: select rows programatically

table/model.go, table/model_test.go, table/query.go, table/query_test.go
Improves #60 
Adds query functions for current highlighted row, whether the table is focused or not, and the current horizontal scroll offset.
Moves `GetVisibleRows` into the query file for consistency, but functionality is unchanged.
=> Add queries for selected row, scrolling, and focused

table/sort_test.go, table/update_test.go
Get `sort` to 100% coverage by ensuring we can mix data types as expected.
=> Extra sort test coverage and remove lingering dead test code

examples/features/main.go, table/model.go, table/options.go, table/row.go, table/view_test.go
Adds an option to show a given indicator when data is not present in the row.  This distinguishes between zero value (such as `""` or `0`) and data that is simply not present in the row data.  Zero value data is shown as expected, but missing data will use the missing data indicator, if supplied.  Supports styled and regular strings.
Closes #102 
Related to #94 discussion
=> Missing data indicator

table/scrolling_test.go, table/update.go
Instead of short-circuiting on the first action found, try to perform any action that matches.  This solves confusing behavior such as scrolling with left/right arrows not working as expected due to the paging action eating the keystroke... even if the table doesn't have any pages!
Closes #104
=> Perform all actions for keybinds, don't short-circuit

.gitignore, table/scrolling.go, table/scrolling_fuzz_test.go, table/scrolling_test.go
Development only requires 1.17, but if we use 1.18 we can take advantage of fuzzing to find more edge cases for scrolling.  This fixes the edge cases found and seems to now be stable/correct for horizontal scrolling edge guard.
Relates to #83
=> Add fuzzing tests for go 1.18 to fix scrolling edge cases

Makefile, README.md, examples/events/README.md, examples/events/main.go, table/events.go, table/events_test.go, table/model.go, table/options.go, table/update.go
Adds a new `UserEvent` type which can be checked after calling `Update` to more easily look for triggers such as the user changing rows.  Currently the only event is a row change event.
=> Add user event for row change

table/events_test.go, table/options.go
There was an edge case where the highlighted row index might be -1 for an empty table.
=> Fix edge case of empty table with row index of -1

table/options.go
Panic occurred when a table was created with no columns and marked with selectable rows.
=> Fix edge case of zero column table with selectable rows panic

table/filter_test.go, table/options.go
Exposes the `SetValue()` function of the filter text input so that filters can be set directly with strings.
Helps #116
=> Allow setting filter value directly with string

table/options.go
When setting the filter input text value, this causes the cursor to appear.  The cursor should not appear.
Helps #116
=> Remove errant cursor when setting filter input manually

table/footer.go
Re-applies an inline version of the base style when using the basic filter text input, which then correctly applies things such as color to the page text.
Fixes #119
=> Fix styling of footer when using base style with filter input

table/query.go, table/query_test.go
Adds query for if the filter input is currently focused, indicating that the user is actively typing into the filter field.  Useful for other controls to know whether they should react to typing or not.
Helps #122
=> Add query for if filter input is currently focused

table/events.go, table/events_test.go, table/update.go
Adds events for when the built-in filter text box is focused or unfocused, allowing the outer app to react to it if needed.
Helps #122
=> Add events for filter input being focused/unfocused

examples/sorting/main.go, table/column.go, table/row.go, table/view_test.go
Helps #126 
Adds a format string option to columns, so that users can provide a string used by `fmt.Sprintf` to display data.  Particularly useful for numeric values that can continue to be sorted.
=> Add format string option to columns

table/filter_test.go
For ensuring #135 is performant.  Results seemed to be extremely quick, and this was confirmed by a locally modified example that had 40,000 rows and allowed filtering, with a pagination size of 10 which was also performant.
```
goos: darwin
goarch: amd64
pkg: github.com/evertras/bubble-table/table
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkPlain3x3TableView-12              23631             50259 ns/op           13334 B/op        348 allocs/op
BenchmarkPlainTableViews/1x1-12           241778              4908 ns/op            1824 B/op         35 allocs/op
BenchmarkPlainTableViews/10x1-12           23725             50341 ns/op           12904 B/op        282 allocs/op
BenchmarkPlainTableViews/1x5-12            65024             18290 ns/op            6506 B/op        142 …
```
=> Add a benchmark for scrolling through a large filtered table

examples/filterapi/main.go, table/filter_test.go, table/options.go
#136 
We were going back to the first page when our built-in filter changed, but not when the provided filter APIs changed.  This makes the behavior consistent across all filtering options.
=> Go to first page on filter API change, same as built-in filter

.gitignore, table/filter.go, table/filter_test.go, table/model.go, table/options.go, table/query.go, table/sort.go, table/update.go
`GetVisibleRows` is being called all over the place.  This function is doing a LOT of calculation for any large data set.  So instead we cache it, and internally invalidate the cache whenever it would change.  This is purely an internal change and seems to massively improve performance when tested.
Helps #135
=> Improve filtered rendering performance

table/query.go, table/query_test.go
This is analog to the `GetHeaderVisibility` function. Note that it only reports if the footer should be visible, but if it has no contents it won't be rendered.
=> Add `Model.GetFooterVisibility` function

examples/filterapi/main.go
Noticed that `cmd` was an ineffectual assignment for https://goreportcard.com/report/github.com/evertras/bubble-table report card, so took some time to fix that as well as a few other style changes while we're here to make it clearer.
=> Fix some linting of filterapi example

table/row.go, table/view_test.go
If a column has a format string, and a row is missing data in that column, an unexpected error is shown.
```go
table.New([]table.Column{
table.NewColumn(columnKeyName, "Name", 13),
table.NewColumn(columnKeyElement, "Element", 10),
table.NewColumn(columnKeyHeight, "Height", 16).WithFormatString("%.2f m"),
}).WithRows([]table.Row{
table.NewRow(table.RowData{
columnKeyName:    "Pikachu",
columnKeyElement: "Electric",
// height is missing
}),
table.NewRow(table.RowData{
columnKeyName:    "Charmander",
columnKeyElement: "Fire",
columnKeyHeight:  0.6,
}),
})
```
```
┏━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃         Name┃   Element┃          Height┃
┣━━━━━━━━━━━━━╋━━━━━━━━━━╋━━━━━━━━━━━━━━━━┫
┃      Pikachu┃  Electric┃  %!f(string=) m┃
┃   Charmander┃      Fire┃          0.60 m┃ …
```
=> Render missing data for columns with format string

table/column.go, table/column_test.go
Expose column fields with read-only access to prevent messing up with bubble tea flow.
https://github.com/Evertras/bubble-table/issues/157
=> Add getters to table.Column

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/lint.yml
The checkout action is 2 versoins behind and Github is grouchy about using very old Node versions for the runners.  So let's update.
=> Update all actions to use checkout v4

table/options.go, table/view_selectable_test.go
Fixes #163 
We were dropping the selected column when using `WithColumns`, so just make sure to add it back in when regenerating columns.
=> Persist selected column when columns are regenerated.

.github/workflows/lint.yml, examples/filter/main.go, table/row.go, table/update.go, table/update_test.go
https://github.com/Evertras/bubble-table/issues/170
Before, we would copy all visible rows over with just the modified row having toggled its select.  However, when filtered, the visible rows did not include all the filtered-out rows, so they would be lost.
Now we keep an internal ID on all rows.  This may also be useful in the future, but it's particularly useful to allow us to find the selected row and toggle its selection directly in the underlying row structure.  This is also quicker and requires less copying, which is a bonus, despite being a simple linear search.
=> Fix bug where selecting a row while filtered would lose all other rows

.golangci.yaml
Removes linters that are deprecated and just being skipped anyway.
=> Remove deprecated linters

README.md, examples/updates/main.go, table/model.go, table/options.go, table/row.go, table/view_test.go
https://github.com/Evertras/bubble-table/issues/173
Adds a way to style a row based on the row index/data, to allow for zebra striping and more dynamic styles based on row data.
=> Add row style func

table/options.go, table/row.go, table/view_test.go
https://github.com/Evertras/bubble-table/issues/173
The highlighted row style was not being applied properly with the new style func.  In hindsight, this is going to be very difficult to properly do, because a highlighted row may need to look different depending on whether it's a zebra stripe, etc.  Therefore, we can just pass the input as a bool to the style func and let the user decide what a highlighted row needs to look like there.
=> Send highlighted status to row style func

.github/workflows/build.yml, .github/workflows/coverage.yml, go.mod
This PR aims to fix https://github.com/Evertras/bubble-table/issues/179 by raising the minimum supported version of go from 1.17 to 1.18.
=> fix: Require at least go 1.18

table/options_test.go
Quick test for coverage and while I'm fidgeting with setting up Go on Windows.
=> Add a test that the default border is actually the default

Makefile, README.md, table/cell.go, table/column.go, table/data.go, table/data_test.go, table/events.go, table/model.go, table/row.go
Minor update to use `any` instead of `interface{}` to better match updated Go standards and make a tool linter stop whining at me about it. :D
=> Update interface{} to any

table/filter.go, table/filter_test.go, table/model.go, table/options.go
https://github.com/user-attachments/assets/7b873b59-ecb5-48b1-bd5a-d1bd28adeffb
I tried this one out in one of my personal projects, and it works nicely! 😄 
Fixes https://github.com/Evertras/bubble-table/issues/195
This also breaks the current `WithFilterFunc` API by requiring to pass `columns []Column` as first argument of the filtering function. This allows for more flexibility and integration of other filter methods.
=> feat: Add `WithFuzzyFilter` to enable fuzzy filter matching

examples/pokemon/main.go, table/cell.go, table/row.go, table/view_test.go
Similar to row style func, add a cell style func that takes in cell data and generate a style dynamically. This allows for easier styling of individual cells based on arbitrary criteria from the user, such as highlighting certain values or column selection.
Updates the pokemon example to highlight this, as generating rows no longer requires specific styling but instead we can highlight the elements based on value.
Should help solve https://github.com/Evertras/bubble-table/issues/201
=> Add cell style func

.github/workflows/codeql-analysis.yml
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
v1 was deprecated back in 2023, whoops. Switch to v2 as recommended.
=> Update CodeQL to v2 due to v1 deprecation

examples/filter/main.go
Closes https://github.com/Evertras/bubble-table/issues/187
The example was erroneously quitting when hitting 'q'. Update the example with how this can be solved by checking if the filter input has focus.
=> Fix filter example when entering 'q' in the text box
